[shell]
program = "/bin/zsh"
args = ["-l"]

[window]
padding = { x = 10, y = 10 }
dynamic_padding = true
opacity = 0.9

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 9